export const mixpanelEvents = {
  VIEW_PROFILE: 'View Profile',
  EDIT_PROFILE: 'Edit Profile',
  EDIT_COURSE: 'Edit Course',
  VIEW_COURSE_PLAYER: 'View Course Player',
  VIEW_COURSE_PAGE: 'View Course Page',
  NEW_BLOG: 'New Blog',
  EDIT_BLOG: 'Edit Blog',
  VIEW_BLOG: 'View Blog',
  NEW_LIVESTREAM: 'New Livestream',
  EDIT_LIVESTREAM: 'Edit Livestream',
  VIEW_LIVESTREAM: 'View Livestream',
  NEW_VIDEO: 'New Video',
  EDIT_VIDEO: 'Edit Video',
  VIEW_VIDEO: 'View Video',
  LOGIN: 'Login',
  REGISTER: 'Register',
  HOMEPAGE: 'Homepage',
};
